name: Build and Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
env:
  PYTHON_VER: 3.11.12-0.3.0
permissions:
  contents: write
jobs:
  build:
    name: Build aarch64 binary
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          sudo apt-get update && sudo apt-get install -y qemu-system-arm binfmt-support qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          echo "Starting pyinstaller build"
          docker run --rm --name builder \
            --platform=aarch64 \
            --user=$(id -u):$(id -g) \
            -v ${GITHUB_WORKSPACE}:/workspace \
            docker.io/unfoldedcircle/r2-pyinstaller:${PYTHON_VER} \
            bash -c \
            "cd /workspace && \
              python -m pip install -r requirements.txt && \
              pyinstaller --clean --onedir --name intg-memcardpro --collect-all zeroconf intg-memcardpro/driver.py"
      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p artifacts/bin
          mv dist/intg-memcardpro/* artifacts/bin
          mv artifacts/bin/intg-memcardpro artifacts/bin/driver
          cp driver.json artifacts/
          VERSION=${GITHUB_REF_NAME:-dev}
          echo "ARTIFACT_NAME=uc-intg-memcardpro-${VERSION}-aarch64" >> $GITHUB_ENV
      - name: Create upload artifact archive
        shell: bash
        run: |
          tar czvf ${{ env.ARTIFACT_NAME }}.tar.gz -C ${GITHUB_WORKSPACE}/artifacts .
          ls -lah
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}.tar.gz
          if-no-files-found: error
          retention-days: 3
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: "*.tar.gz"
